name: Go Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # strategy:
    #   matrix:
    #     go: [ '1.15', '1.16', '1.17', '1.18' ]
    #     os: [ ubuntu-latest, macos-latest, windows-latest ]
    name: Go Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          check-latest: true
      - name: Download dependencies
        run: go mod tidy
      - name: Run tests
        run: |
          pwd
          ls
          go test `go list ./... | grep -v db`