name: Go Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          check-latest: true
      - name: Download dependencies
        run: go mod tidy
      - name: Run tests
        run: go test `go list ./... | grep -v db`