name: Go Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        go: [ '1.15', '1.16', '1.17', '1.18' ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    name: Go ${{ matrix.go }} On ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
      - name: Download dependencies
        run: go mod tidy
      - name: Run tests
        run: go test `go list ./... | grep -v db`